NUM_DRAWS_AMPLITUDES_DIFF_HARMONICS = 100

MIN_SAMPLES_IN_INTERVAL_LIMITER = 2

EXTRACT_AMPLITUDES_NOISE_PARAMS = {
    'mean': 0,
    'var': 1,
}
MAX_DIST_IN_STANDARD_DEVIATION = 4

MAX_FAILURE_TRANS_SAMPLES = 500
MIN_FAILURE_TRANS_SAMPLES = 200
GAP_FROM_START_END_TRANS_SAMPLES = 200
